src/main/java/br/com/casadocodigo/loja/models/CarrinhoCompras.java
package br.com.casadocodigo.loja.models;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Collection;
import java.util.LinkedHashMap;
import java.util.Map;

import org.springframework.context.annotation.Scope;
import org.springframework.context.annotation.ScopedProxyMode;
import org.springframework.stereotype.Component;
import org.springframework.web.context.WebApplicationContext;

@Component
@Scope(value=WebApplicationContext.SCOPE_SESSION, proxyMode=ScopedProxyMode.TARGET_CLASS)
public class CarrinhoCompras implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	private Map<CarrinhoItem, Integer> itens = new LinkedHashMap<CarrinhoItem, Integer>();

	public Collection<CarrinhoItem> getItens() {
		return itens.keySet();
	}
	
	public void add(CarrinhoItem item) {
		itens.put(item, getQuantidade(item) + 1);
	}

	public Integer getQuantidade(CarrinhoItem item) {
		if(!itens.containsKey(item)) {
			itens.put(item, 0);
		}
		return itens.get(item);
	}
	
	public int getQuantidade() {
		return itens.values().stream().reduce(0, (proximo, acumulador) -> proximo + acumulador);
	}
	
	public BigDecimal getTotal(CarrinhoItem item) {
		return item.getTotal(getQuantidade(item));
	}
	
	public BigDecimal getTotal() {
		BigDecimal total = BigDecimal.ZERO;
		for (CarrinhoItem item : itens.keySet()) {
			total = total.add(getTotal(item));
		}
		return total;
	}

	public void remover(Integer produtoId, TipoPreco tipoPreco) {
		Produto produto = new Produto();
		produto.setId(produtoId);
		itens.remove(new CarrinhoItem(produto, tipoPreco));
	}
}

src/main/java/br/com/casadocodigo/loja/controller/HomeController.java
package br.com.casadocodigo.loja.controller;

import java.util.Arrays;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.stereotype.Controller;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.servlet.ModelAndView;

import br.com.casadocodigo.loja.daos.ProdutoDAO;
import br.com.casadocodigo.loja.daos.UsuarioDAO;
import br.com.casadocodigo.loja.models.Produto;
import br.com.casadocodigo.loja.models.Role;
import br.com.casadocodigo.loja.models.Usuario;

@Controller
public class HomeController {
	
	@Autowired
	private ProdutoDAO produtoDao;
	
	@Autowired
	private UsuarioDAO usuarioDAO;
	
	@RequestMapping("/")
	@Cacheable(value="produtoHome")
	public ModelAndView index() {
		List<Produto> produtos = produtoDao.listar();
		ModelAndView modelAndView = new ModelAndView("/home");
		modelAndView.addObject("produtos", produtos);		
		return modelAndView;
	}
	
	@Transactional
	@ResponseBody
	@RequestMapping("/url-magica-uieruiquriqweoru758438rt87t2purioeuroqwiuy")	
	public String urlMagica() {
		Usuario usuario = new Usuario();
		usuario.setNome("Admin");
		usuario.setEmail("admin@casadocodigo.com.br");
		usuario.setSenha("$2a$10$lt7pS7Kxxe5JfP.vjLNSyOXP11eHgh7RoPxo5fvvbMCZkCUss2DGu");
	    usuario.setRoles(Arrays.asList(new Role("ROLE_ADMIN")));

		usuarioDAO.gravar(usuario);		
		
		return "Url Mágica executada";
	}
}

src/main/java/br/com/casadocodigo/loja/controller/loginController.java
package br.com.casadocodigo.loja.controller;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@Controller
public class loginController {

	@RequestMapping(value="/login", method=RequestMethod.GET)
	public String loginForm() {
		return "/loginForm";
	}
}

src/main/webapp/WEB-INF/views/cabecalho.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt"%>
<%@ taglib uri="http://www.springframework.org/tags" prefix="s"%>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<%@ taglib uri="http://www.springframework.org/security/tags" prefix="security"%>

<header id="layout-header">
	<div class="clearfix container">
		<a href="${s:mvcUrl('HC#index').build()}" id="logo"> </a>
		<div id="header-content">
			<nav id="main-nav">
				<ul class="clearfix">
					<security:authorize access="hasRole('ROLE_ADMIN')">
						<li><a href="${s:mvcUrl('PC#listar').build()}" rel="nofollow">Lista</a></li>
						<li><a href="${s:mvcUrl('PC#form').build()}" rel="nofollow">Produtos</a></li>
					</security:authorize>
					<li><a href="${s:mvcUrl('CCC#itens').build()}" rel="nofollow">
						<fmt:message key="menu.carrinho">
							<fmt:param value="${carrinhoCompras.quantidade}" />
						</fmt:message>
						<!--
							<s:message code="menu.carrinho" arguments="${carrinhoCompras.quantidade}"></s:message> 
						 -->						
					</a></li>
					<li><a href="?locale=pt_BR" rel="nofollow"><fmt:message key="menu.pt" /></a></li>
					<li><a href="?locale=en_US" rel="nofollow"><fmt:message key="menu.en" /></a></li>							
				</ul>
			</nav>
		</div>
	</div>
</header>
<nav class="categories-nav">
	<ul class="container">
		<li class="category"><a href="http://www.casadocodigo.com.br"><fmt:message key="navegacao.categoria.home" /></a></li>
		<li class="category"><a href="/collections/livros-de-agile"><fmt:message key="navegacao.categoria.agile" /></a></li>
		<li class="category"><a href="/collections/livros-de-front-end"><fmt:message key="navegacao.categoria.front_end" /></a></li>
		<li class="category"><a href="/collections/livros-de-games"><fmt:message key="navegacao.categoria.games" /></a></li>
		<li class="category"><a href="/collections/livros-de-java"><fmt:message key="navegacao.categoria.java" /></a></li>
		<li class="category"><a href="/collections/livros-de-mobile"><fmt:message key="navegacao.categoria.mobile" /></a></li>
		<li class="category"><a href="/collections/livros-desenvolvimento-web"><fmt:message key="navegacao.categoria.web" /></a></li>
		<li class="category"><a href="/collections/outros"><fmt:message key="navegacao.categoria.outros" /></a></li>
	</ul>
</nav>

src/main/webapp/WEB-INF/views/loginForm.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://www.springframework.org/tags" prefix="s"%>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<!DOCTYPE html>
<html>
<head>
<c:url value="/resources/css" var="cssPath" />
<meta charset="UTF-8">
<title>Livros de Java, Android, Iphone, Ruby e muito mais - Casa do Código</title>
<link rel="stylesheet" href="${cssPath}/bootstrap.min.css">
<style type="text/css">
    body {
        padding-bottom: 60px;
    }
</style>
</head>
<body>
	<div class="container">
		<h1>Login da Casa do Código</h1>
		<form:form servletRelativeAction="/login" method="POST">
			<div class="form-group">
				<label>Email:</label>
				<input name="username" type="text" class="form-control" />
			</div>
			<div class="form-group">
				<label>Senha:</label>
				<input name="password" type="password" class="form-control" />
			</div>
			<button type="submit" class="btn btn-primary">Logar</button>
		</form:form>
	</div>
</body>
</html>